use crate::managed_agents::HarnessSource;

use super::runtime_metadata::{KnownAcpRuntime, RuntimeAuthentication, RuntimeReadinessPolicy};

pub(super) const GOOSE_AVATAR_URL: &str = "https://goose-docs.ai/img/logo_dark.png";
pub(super) const CLAUDE_CODE_AVATAR_URL: &str = "https://anthropic.gallerycdn.vsassets.io/extensions/anthropic/claude-code/2.1.77/1773707456892/Microsoft.VisualStudio.Services.Icons.Default";
pub(super) const CODEX_AVATAR_URL: &str = "https://openai.gallerycdn.vsassets.io/extensions/openai/chatgpt/26.5313.41514/1773706730621/Microsoft.VisualStudio.Services.Icons.Default";
pub(super) const BUZZ_AGENT_AVATAR_URL: &str =
    "https://raw.githubusercontent.com/kingkillery/pkzz/refs/heads/main/crates/buzz-agent/buzz-agent.png";

pub(super) const KNOWN_ACP_RUNTIMES: &[KnownAcpRuntime] = &[
    KnownAcpRuntime {
        id: "goose",
        label: "Goose",
        commands: &["goose"],
        aliases: &[],
        avatar_url: GOOSE_AVATAR_URL,
        source: HarnessSource::Builtin,
        default_args: &["acp"],
        mcp_command: None,
        mcp_hooks: false,
        underlying_cli: Some("goose"),
        cli_install_commands: &["curl -fsSL https://github.com/aaif-goose/goose/releases/download/stable/download_cli.sh | CONFIGURE=false bash"],
        // Goose's stable release currently publishes only the Unix installer;
        // its official Windows instructions intentionally point at this main-branch script.
        cli_install_commands_windows: &[windows_install_command!("goose", "https://raw.githubusercontent.com/aaif-goose/goose/main/download_cli.ps1", "$env:CONFIGURE='false'; ")],
        adapter_install_commands: &[],
        cli_install_instructions_url: "https://goose-docs.ai/docs/getting-started/installation/",
        adapter_install_instructions_url: "",
        cli_install_hint: "Pkzz talks to Goose through the Goose CLI.",
        adapter_install_hint: "",
        skill_dir: Some(".goose/skills"),
        supports_acp_model_switching: false,
        model_env_var: Some("GOOSE_MODEL"),
        provider_env_var: Some("GOOSE_PROVIDER"),
        provider_locked: false,
        default_env: &[("GOOSE_MODE", "auto")],
        config_file_path: Some("~/.config/goose/config.yaml"),
        config_file_format: Some("yaml"),
        supports_acp_native_config: true,
        thinking_env_var: Some("GOOSE_THINKING_EFFORT"),
        max_tokens_env_var: Some("GOOSE_MAX_TOKENS"),
        context_limit_env_var: Some("GOOSE_CONTEXT_LIMIT"),
        max_rounds_env_var: None,
        required_normalized_fields: &["model", "provider"],
        authentication: RuntimeAuthentication::NotApplicable,
        readiness_policy: RuntimeReadinessPolicy::AvailabilityOnly,
    },
    KnownAcpRuntime {
        id: "claude",
        label: "Claude Code",
        commands: &["claude-agent-acp", "claude-code-acp"],
        aliases: &["claude-code", "claudecode"],
        avatar_url: CLAUDE_CODE_AVATAR_URL,
        source: HarnessSource::Builtin,
        default_args: &[],
        mcp_command: None,
        mcp_hooks: false,
        underlying_cli: Some("claude"),
        cli_install_commands: &["curl -fsSL https://claude.ai/install.sh | bash"],
        cli_install_commands_windows: &[windows_install_command!("claude", "https://claude.ai/install.ps1")],
        adapter_install_commands: &["npm install -g @agentclientprotocol/claude-agent-acp"],
        cli_install_instructions_url: "https://code.claude.com/docs/en/getting-started",
        adapter_install_instructions_url: "https://github.com/agentclientprotocol/claude-agent-acp",
        cli_install_hint: "Pkzz talks to Claude Code through the Claude Code CLI.",
        adapter_install_hint: "Pkzz talks to the Claude Code CLI through an ACP adapter. Install it with: npm install -g @agentclientprotocol/claude-agent-acp.",
        skill_dir: Some(".claude/skills"),
        supports_acp_model_switching: false,
        model_env_var: None,
        provider_env_var: None,
        provider_locked: true,
        default_env: &[],
        config_file_path: Some("~/.claude/settings.json"),
        config_file_format: Some("json"),
        supports_acp_native_config: false,
        thinking_env_var: None,
        max_tokens_env_var: None,
        context_limit_env_var: None,
        max_rounds_env_var: None,
        required_normalized_fields: &[],
        authentication: RuntimeAuthentication::CliProbe {
            args: &["claude", "auth", "status"],
            login_hint: "Run the Claude CLI to complete authentication.",
        },
        readiness_policy: RuntimeReadinessPolicy::Authentication,
    },
    KnownAcpRuntime {
        id: "codex",
        label: "Codex",
        commands: &["codex-acp"],
        aliases: &[],
        avatar_url: CODEX_AVATAR_URL,
        source: HarnessSource::Builtin,
        default_args: &[],
        mcp_command: Some("buzz-dev-mcp"),
        mcp_hooks: false,
        underlying_cli: Some("codex"),
        cli_install_commands: &["curl -fsSL https://chatgpt.com/codex/install.sh | sh"],
        cli_install_commands_windows: &[windows_install_command!("codex", "https://chatgpt.com/codex/install.ps1")],
        adapter_install_commands: &["npm install -g @agentclientprotocol/codex-acp"],
        cli_install_instructions_url: "https://developers.openai.com/codex/cli/",
        adapter_install_instructions_url: "https://github.com/agentclientprotocol/codex-acp",
        cli_install_hint: "Pkzz talks to Codex through the Codex CLI.",
        adapter_install_hint: "Pkzz talks to the Codex CLI through an ACP adapter. Install it with: npm install -g @agentclientprotocol/codex-acp.",
        skill_dir: Some(".codex/skills"),
        supports_acp_model_switching: false,
        model_env_var: None,
        provider_env_var: None,
        provider_locked: false,
        default_env: &[],
        config_file_path: Some("~/.codex/config.toml"),
        config_file_format: Some("toml"),
        supports_acp_native_config: false,
        thinking_env_var: None,
        max_tokens_env_var: None,
        context_limit_env_var: None,
        max_rounds_env_var: None,
        required_normalized_fields: &[],
        authentication: RuntimeAuthentication::CliProbe {
            args: &["codex", "login", "status"],
            login_hint: "Run `codex login` to authenticate.",
        },
        readiness_policy: RuntimeReadinessPolicy::Authentication,
    },
    KnownAcpRuntime {
        id: "buzz-agent",
        label: "Pkzz Agent",
        commands: &["buzz-agent"],
        aliases: &[],
        avatar_url: BUZZ_AGENT_AVATAR_URL,
        source: HarnessSource::Builtin,
        default_args: &[],
        mcp_command: Some("buzz-dev-mcp"),
        mcp_hooks: true,
        underlying_cli: None,
        cli_install_commands: &[],
        cli_install_commands_windows: &[],
        adapter_install_commands: &[],
        cli_install_instructions_url: "https://github.com/kingkillery/pkzz",
        adapter_install_instructions_url: "https://github.com/kingkillery/pkzz",
        cli_install_hint: "Ships with the Pkzz desktop app.",
        adapter_install_hint: "",
        skill_dir: None,
        supports_acp_model_switching: true,
        model_env_var: Some("BUZZ_AGENT_MODEL"),
        provider_env_var: Some("BUZZ_AGENT_PROVIDER"),
        provider_locked: false,
        default_env: &[],
        config_file_path: None,
        config_file_format: None,
        supports_acp_native_config: false,
        thinking_env_var: Some("BUZZ_AGENT_THINKING_EFFORT"),
        max_tokens_env_var: Some("BUZZ_AGENT_MAX_OUTPUT_TOKENS"),
        context_limit_env_var: Some("BUZZ_AGENT_MAX_CONTEXT_TOKENS"),
        max_rounds_env_var: Some("BUZZ_AGENT_MAX_ROUNDS"),
        required_normalized_fields: &["model", "provider"],
        authentication: RuntimeAuthentication::NotApplicable,
        readiness_policy: RuntimeReadinessPolicy::AvailabilityOnly,
    },
    KnownAcpRuntime {
        id: "ompk",
        label: "Oh My PK",
        // OMPK's `ompk` bin is fork-specific. Upstream OMP remains the
        // separate flat `omp` preset and must never satisfy this descriptor.
        commands: &["ompk"],
        aliases: &[],
        // Rich metadata does not elevate the preset to a remote icon/trust source.
        avatar_url: "",
        source: HarnessSource::Preset,
        default_args: &["acp"],
        mcp_command: None,
        mcp_hooks: false,
        underlying_cli: None,
        cli_install_commands: &[],
        cli_install_commands_windows: &[],
        adapter_install_commands: &[],
        cli_install_instructions_url: "https://github.com/kingkillery/oh-my-pk",
        adapter_install_instructions_url: "",
        cli_install_hint: "Pkzz talks to Oh My PK through its CLI's ACP mode (ompk acp).",
        adapter_install_hint: "",
        skill_dir: None,
        supports_acp_model_switching: true,
        model_env_var: None,
        provider_env_var: None,
        provider_locked: false,
        default_env: &[],
        config_file_path: None,
        config_file_format: None,
        supports_acp_native_config: false,
        thinking_env_var: None,
        max_tokens_env_var: None,
        context_limit_env_var: None,
        max_rounds_env_var: None,
        required_normalized_fields: &[],
        authentication: RuntimeAuthentication::AcpMethods {
            login_hint: "Sign in from a terminal with `ompk auth-broker login anthropic` (also `cursor`, `openai-codex`), or run `ompk` and use `/login`.",
        },
        readiness_policy: RuntimeReadinessPolicy::AcpModelCatalog,
    },
    KnownAcpRuntime {
        id: "cline",
        label: "Cline",
        // Cline speaks ACP natively via `cline --acp`; there is no adapter to
        // install. Verified against a live initialize handshake (agentInfo
        // name "cline"), which also advertises its three auth methods.
        commands: &["cline"],
        aliases: &[],
        avatar_url: "",
        source: HarnessSource::Preset,
        default_args: &["--acp"],
        // Cline manages its own MCP servers (`cline mcp`); Pkzz injects none.
        mcp_command: None,
        mcp_hooks: false,
        underlying_cli: None,
        cli_install_commands: &["npm install -g cline"],
        cli_install_commands_windows: &["npm install -g cline"],
        adapter_install_commands: &[],
        cli_install_instructions_url: "https://github.com/cline/cline",
        adapter_install_instructions_url: "",
        cli_install_hint: "Pkzz talks to Cline through its CLI's ACP mode (cline --acp).",
        adapter_install_hint: "",
        skill_dir: None,
        // Cline advertised no ACP model-catalog capability at initialize, so
        // Pkzz must not claim switching it cannot perform.
        supports_acp_model_switching: false,
        model_env_var: None,
        provider_env_var: None,
        provider_locked: false,
        default_env: &[],
        config_file_path: None,
        config_file_format: None,
        supports_acp_native_config: false,
        thinking_env_var: None,
        max_tokens_env_var: None,
        context_limit_env_var: None,
        max_rounds_env_var: None,
        required_normalized_fields: &[],
        authentication: RuntimeAuthentication::AcpMethods {
            login_hint: "Sign in from Pkzz (Cline, ClinePass, or ChatGPT Subscription), or from a terminal with `cline auth`.",
        },
        // Readiness stops at authentication: Cline exposes no ACP model
        // catalog to probe.
        readiness_policy: RuntimeReadinessPolicy::Authentication,
    },
];
